version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app_network

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./.neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/password


networks:
  app_network: {}
