name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  health-check:
    name: Type-check and lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Health-check
        run: pnpm health-check

  docker:
    name: Build docker container
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build docker container
        run: docker compose build web
